### PR TITLE
add ssl support

### PR DESCRIPTION
**Pull request by hieudbui**

### CODE REVIEW

**Comment by hieudbui** [comment]
I installed it locally and pointed it to my compose redis instance that has ssl support

**Comment by lkwg82** [comment]
So, how do we know, we dont break it while refactoring? I think in terms of CI.

**Comment by hieudbui** [comment]
I don't think a unit test makes sense in this case.  If that is what you are thinking as CI.
I suppose using a spy is possible but that requires refactoring the JedisPoolFactory.  The solution is an integration test, but that requires running redis with a proxy supporting ssl termination.
However that is not realistic expectation.  At this point, I would say that the code is reviewed and was manually verified.

**Comment by mgerlach** [comment]
I can try to find some time to test this with a redis installation with SSL support. Not sure when I get around to doing so, though, so if anybody feels like verifying this quickly, go ahead and post your result here...

**Comment by mgerlach** [comment]
... however the change looks like it is certainly backward compatible, so without SSL, we should definitely be fine. As @hieudbui tested it with SSL, I'd expect it to work, too. Would still like to try it out. @hieudbui can you give a quick step-by-step explanation of what you had to do to successfully write to Redis with SSL?

**Comment by hieudbui** [comment]
First I install the changes to my local repo.
Then in logback.groovy I set RedisConnectionConfig.ssl to true, RedisConnectionConfig.host is pointed to a ssl enabled redis proxy.

Starts up the server and use redis-cli to verify that logs are written to redis.

**Comment by hieudbui** [comment]
Anything else you need to get this PR merged?

**Comment by doernbrackandre** [comment]
@hieudbui thanks for your contribution. It will be part of the next release.

**Comment by malcolmrobbins** [comment]
Hi,
I'm trying to use this appender with SSL but it's not at all obvious to me how to configure the redis appender for SSL, presumably because the doco lags the code capability, but even when I debug the code it's not clear how it gets its SSL configuration.  Can someone provide a few pointers?

**Pull request merged**
